import streamlit as st
import api_client
from datetime import datetime
import pandas as pd

@st.fragment(run_every="30s")
def render():

    user = st.session_state.user
    lga = user.get('location_lga', 'Unknown')
    role = user.get('role', 'CITIZEN')
    
    # --- SUB-NAVIGATION (Consolidated Header) ---
    st.markdown("### 🔍 Health Intelligence Hub")
    sub_view = st.segmented_control(
        "Navigation", 
        ["Main Inbox", "Executive Briefing", "Intelligence Trends"],
        default="Main Inbox",
        label_visibility="collapsed"
    )
    
    st.divider()

    try:
        # Use cached alerts from app.py
        alerts = st.session_state.get("cached_alerts")
        if not alerts:
            alerts = api_client.get_alerts()

        if not isinstance(alerts, list):
            st.error("Intelligence network is resetting. Please wait...")
            return

        # --- VIEW 1: EXECUTIVE BRIEFING (Tailored Insights) ---
        if sub_view == "Executive Briefing":
            st.markdown(f"#### 📅 Situational Briefing for {datetime.now().strftime('%d %B %Y')}")
            with st.status("🧠 Generating your tailored briefing...", expanded=True) as status:
                briefing_res = api_client.get_briefing(lga=lga, role=role)
                status.update(label="✅ Briefing Complete", state="complete")

            if isinstance(briefing_res, dict) and not briefing_res.get("error"):
                # Generative AI Insight
                ai_insight = briefing_res.get("ai_insight")
                if ai_insight:
                    with st.container(border=True):
                        st.markdown("### 🤖 Generative Intelligence")
                        st.info(ai_insight)
                        st.caption("✨ *Self-correcting briefing generated by Gemini 1.5 Flash based on local database signals.*")
                
                items = briefing_res.get("briefing", [])
                total = briefing_res.get("alerts_count", 0)
                st.caption(f"📊 {total} active signals in your area | Role: {role} | LGA: {lga}")
                if items:
                    for item in items:
                        risk = item.get("risk_level", "Low")
                        colour = {"Critical": "🔴", "High": "🟠", "Moderate": "🟡", "Low": "🟢"}.get(risk, "🔵")
                        verified = "✅ Verified" if item.get("verified") else "⏳ Pending"
                        with st.container(border=True):
                            st.markdown(f"**{colour} {item.get('disease','General')}** · {item.get('location','Lagos')} · {verified}")
                            st.write(item.get("text", "No details available."))
                else:
                    st.info("No active signals in your area right now. All clear for your LGA.")
            else:
                st.error("Could not load briefing. Backend may be offline.")
            st.info(f"💡 *Tailored to: Lagos/{lga} · Role: {role}*")
            return

        # --- VIEW 2: INTELLIGENCE TRENDS (Restored Graph) ---
        if sub_view == "Intelligence Trends":
            st.markdown("#### 📈 Signal Acquisition Trends (Last 7 Days)")
            if alerts:
                # Guard: only include alerts with valid timestamps
                valid_alerts = [a for a in alerts if isinstance(a, dict) and a.get('timestamp')]
                if valid_alerts:
                    df_alerts = pd.DataFrame(valid_alerts)
                    df_alerts['date'] = pd.to_datetime(df_alerts['timestamp'], errors='coerce').dt.date
                    df_alerts = df_alerts.dropna(subset=['date'])
                    trend_data = df_alerts.groupby('date').size().reset_index(name='Signals')
                    st.bar_chart(trend_data.set_index('date'), color="#0ea5e9")
                    st.caption("Monitoring signal volume across 22 acquisition nodes.")
                else:
                    st.info("No alerts with valid timestamps to visualize.")
            else:
                st.info("No historical data to visualize yet.")
            return

        # --- VIEW 3: MAIN INBOX (Single Display Table/Detail View) ---
        if not alerts:
            st.info("Your inbox is empty. The autonomous agents are currently scanning 22 sources for new signals.")
            return

        last_check = st.session_state.get('last_checked_alerts', '1970-01-01T00:00:00')
        
        display_data = []
        for a in alerts:
            ts = str(a.get('timestamp') or '')
            created_ts = str(a.get('created_at') or ts)
            is_new = created_ts > last_check
            is_local = str(a.get('location_text')) == lga
            
            display_data.append({
                "ID": a.get('alert_id'),
                "Status": "🆕 NEW" if is_new else "✅ Seen",
                "Priority": "📍 LOCAL" if is_local else "🌐 Global",
                "Disease": a.get('disease') or "General Health",
                "Location": a.get('location_text') or "Lagos",
                "Source": a.get('source', 'Unknown'),
                "Risk": a.get('risk_level', 'Low'),
                "Date": ts.replace('T', ' ').split(' ')[0] if (' ' in ts or 'T' in ts) else ts,
                "_sort_time": ts,
                "_full_data": a
            })
        
        df = pd.DataFrame(display_data)
        # Sort for grouping
        df['is_new_val'] = df['Status'] == "🆕 NEW"
        df['is_local_val'] = df['Priority'] == "📍 LOCAL"
        df = df.sort_values(by=['is_new_val', 'is_local_val', '_sort_time'], ascending=[False, False, False])

        new_df = df[df['is_new_val']]
        older_df = df[~df['is_new_val']]

        if not new_df.empty:
            st.subheader("🆕 Fresh Intelligence")
            st.dataframe(
                new_df.drop(columns=['is_new_val', 'is_local_val', '_sort_time', '_full_data']),
                use_container_width=True,
                hide_index=True
            )
        
        if not older_df.empty:
            st.subheader("📜 Historical Context")
            st.dataframe(
                older_df.drop(columns=['is_new_val', 'is_local_val', '_sort_time', '_full_data']),
                use_container_width=True,
                hide_index=True
            )

        # Focused Search/Filter
        search_q = st.text_input("🔍 Filter signals by disease or location...", placeholder="e.g. Cholera")
        if search_q:
            df = df[df['Disease'].str.contains(search_q, case=False) | df['Location'].str.contains(search_q, case=False)]

        # Selection for Single Display (using the modified dataframe)
        selected_index = st.selectbox(
            "Select Intelligence Signal to Expand:",
            options=df.index,
            format_func=lambda x: f"{df.loc[x, 'Status']} | {df.loc[x, 'Priority']} | {df.loc[x, 'Disease']} @ {df.loc[x, 'Location']}"
        )

        if selected_index is not None:
            item = df.loc[selected_index, "_full_data"]
            
            st.markdown(f"### 🛡️ {item.get('disease')} Intelligence Detail")
            
            inner_col1, inner_col2 = st.columns([3, 1])
            with inner_col1:
                st.write(f"**Original Headline:** {item.get('text')}")
                
                summary = item.get('summary')
                is_ai = item.get('ai_powered', False)
                
                if summary:
                    badge = "🤖 **AI Analysis**" if is_ai else "📝 **System Summary**"
                    st.success(f"{badge}\n\n{summary}")
                    if is_ai:
                        st.caption("✨ *Generative clinical reasoning provided by Gemini 1.5 Flash.*")
                else:
                    st.warning("🤖 **Intelligence Layer**: This signal is currently in the AI processing queue. Refresh shortly for deep analysis.")

            with inner_col2:
                risk_lvl = item.get('risk_level', 'Low')
                st.metric("Risk Assessment", risk_lvl)
                st.caption(f"📍 **Target LGA:** {item.get('location_text')}")
                st.caption(f"🛰️ **Capture Node:** {item.get('source')}")
                if st.button("🔗 Open Source", width='stretch'):
                    st.write("Source URL restriction active.")
                
                if st.button("📖 Get Deeper Context (RAG)", width='stretch'):
                    with st.spinner("Retrieving intelligence..."):
                        q = f"Latest protocols and news for {item.get('disease')} in {item.get('location_text')}"
                        r = api_client.advisory_search(q)
                        if r and not r.get("error"):
                            st.session_state[f"rag_context_{item.get('alert_id')}"] = r
                
                rag_data = st.session_state.get(f"rag_context_{item.get('alert_id')}")
                if rag_data:
                    with st.expander("🌐 Intelligence Context", expanded=True):
                        st.caption(f"Source: {rag_data.get('source').upper()}")
                        for rss in rag_data.get('results', [])[:2]:
                            st.write(rss.get('content') or rss.get('snippet') or str(rss))

        st.divider()
        
        # Update last checked timestamp
        st.session_state.last_checked_alerts = datetime.utcnow().isoformat()
        
    except Exception as e:
        st.error(f"Intelligence Interface Error: {e}")
